### ISSUE TITLE
[Question]Support for additional table types and contributor guidelines 关于未来表类型支持和贡献者指引

### ISSUE THREAD

**Issue by dingxin-tech** [winwin-inc/dbt-odps#3]
Dear maintainers,

First of all, I want to thank you for the excellent work on [dbt-odps](https://github.com/winwin-inc/dbt-odps). This project has been incredibly useful for us. I have a couple of questions that I hope you can address:

1. Is there any plan to support currently unsupported table types (such as partitioned tables and cluster tables)?
We have noticed that in the current version, [dbt-odps](https://github.com/winwin-inc/dbt-odps) does not seem to support certain types of tables (e.g., partitioned tables, cluster tables). Could you please let us know if there are any plans to add support for these table types in the future? If so, is there a rough timeline or roadmap available?

2. Does the project welcome contributors, and is there a plan to add a license?
We highly appreciate the project and are eager to contribute to it. However, we have noticed that the repository currently doesn't have a clear open-source license. This brings up some concerns about using and contributing to the code. We would appreciate it if you could answer the following questions:

Once again, thank you for all your hard work and dedication! Looking forward to your response.

Best regards,

Jason Zhang

----
亲爱的项目维护者们，

首先，非常感谢您们为[dbt-odps](https://github.com/winwin-inc/dbt-odps)所做的工作，使这个项目对我们而言十分有用。在此，我有几个关心的问题，希望能够得到解答：

1. 该项目是否有计划支持目前不支持的表类型（如分区表、cluster表）？
我们发现在现有版本中，[dbt-odps](https://github.com/winwin-inc/dbt-odps) 似乎不支持某些特定类型的表（例如分区表、cluster表）。我想了解一下未来是否计划添加对此类表的支持。如果是，是否有大致的时间表或者路线图可以参考？

2. 该项目是否欢迎贡献者，是否应该增加一个license？
我们非常欣赏这个项目，并希望能够对其做出贡献。但是我们注意到当前仓库中没有明确的开源许可协议（license）。这使得我们在使用和贡献代码之前有些疑虑。希望能够得到以下问题的解答：

再次感谢您们的辛勤工作和付出！期待您的回复。

祝好！

Jason Zhang

**Comment by leezhongshan** [comment]
@dingxin-tech 谢谢您宝贵建议

1. 分区表可以这样配置


- name: dbt_demo_incremental
    description: '{{doc("dbt_demo_incremental")}}'
    config:
      materialized: incremental
      incremental_strategy: insert_overwrite
      on_schema_change: fail
      partition_by:
        - field: ds
          data_type: string
          comment: the date partition


with source as (
    select
        '2' as id,
        '20210101' as ds
    union all
    select
        '3' as id,
        '20220201' as ds
)

select *
from source

2.  已经添加
